#!/usr/bin/env bash
set -e # halt script on error

openssl aes-256-cbc -K $encrypted_f05b37f4d69b_key -iv $encrypted_f05b37f4d69b_iv -in .travis/deploy-key.enc -out .travis/deploy-key -d
eval "$(ssh-agent -s)" #start the ssh agent
chmod 600 .travis/deploy-key
ssh-add .travis/deploy-key
git config --global push.default simple
git remote add gh-pages git@github.com:strategicdata/strategicdata.com.au.git
git checkout gh-pages
git pull
git merge master -m "Travic CI deployment"
git push
