#!/usr/bin/env bash
set -e # halt script on error

eval "$(ssh-agent -s)" #start the ssh agent
chmod 600 .travis/deploy-key
ssh-add .travis/deploy-key
git config --global push.default simple
git remote add gh-pages git@github.com:strategicdata/strategicdata.com.au.git
git push gh-pages HEAD:gh-pages
