#!/usr/bin/env bash

set -e # halt script on error

openssl aes-256-cbc \
  -K $encrypted_f05b37f4d69b_key \
  -iv $encrypted_f05b37f4d69b_iv \
  -in .travis/deploy-key.enc \
  -out .travis/deploy-key -d

eval "$(ssh-agent -s)" #start the ssh agent
chmod 600 .travis/deploy-key
ssh-add .travis/deploy-key

# Edit .gitignore to publish
perl -n -i -e "print unless /^_site\/$/" ./.gitignore
git add .
git commit -m "Commit build artefacts for publishing"
git remote add pages git@github.com:strategicdata/strategicdata.com.au.git
git push pages `git subtree split --prefix _site 2> /dev/null`:gh-pages --force
git reset HEAD~
git checkout .gitignore
